### ISSUE TITLE
The scaling factor between the coordinate system of the vertices in obj and the real world coordinate system

### ISSUE THREAD

**Issue by ForrestPi** [unclearness/blendshape_line2d_fitting#3]
Hi  have you tested the EyelidModel?  is the unit is mm?  
I used to reconstruct two views of left and right eye picture.
but I cannot get the corrected  reconstructed mesh.
have you tried to fit with multi-view ?
<img width="258" alt="image" src="https://user-images.githubusercontent.com/12846142/164200324-b1a86d18-67ba-4aa0-aaf5-b091d1400b64.png">

**Comment by unclearness** [comment]
I used orthogonal projection with pixel-unit in my demo.py because I don't know the camera parameters of a test image taken from the internet. It works fine for a single view.
Although the original paper is designed for a single view, a multi-view fitting would be possible.
If you want to fit the eyelid model to multi-view images, you need to implement proper projection with pre-calibrated camera parameters (intrinsic and extrinsic) of each view.
